# user sub map
ADV_REG_INPUT_CONTROL = 0x00

ADV_REG_VIDEO_SELECTION_1 = 0x01
ADV_REG_VIDEO_SELECTION_2 = 0x02
ADV_REG_OUTPUT_CONTROL = 0x03

ADV_REG_EXTENDED_OUTPUT_CONTROL__RW = 0x04
ADV_REG_AUTODETECT_ENABLE = 0x07

ADV_REG_CONTRAST = 0x08
ADV_REG_BRIGHTNESS = 0x0A
ADV_REG_HUE = 0x0B

ADV_REG_DEFAULT_VALUE_Y = 0x0C
ADV_REG_DEFAULT_VALUE_C = 0x0D
ADV_REG_ADI_CONTROL_1 = 0x0E
ADV_REG_POWER_MANAGEMENT = 0x0F
ADV_REG_STATUS_1 = 0x10
ADV_REG_IDENT = 0x11
ADV_REG_STATUS_2 = 0x12
ADV_REG_STATUS_3 = 0x13
ADV_REG_ANALOG_CLAMP_CONTROL = 0x14
ADV_REG_DIGITAL_CLAMP_CONTROL_1 = 0x15

ADV_REG_SHAPING_FILTER_CONTROL_1 = 0x17
ADV_REG_SHAPING_FILTER_CONTROL_2 = 0x18

ADV_REG_COMB_FILTER_CONTROL = 0x19

ADV_REG_ADI_CONTROL_2 = 0x1D
ADV_REG_PIXEL_DELAY_CONTROL = 0x27

ADV_REG_MISC_GAIN_CONTROL = 0x2B
ADV_REG_AGC_MODE_CONTROL = 0x2C

ADV_REG_CHROMA_GAIN_CONTROL_1 = 0x2D
ADV_REG_CHROMA_GAIN_CONTROL_2 = 0x2E

ADV_REG_LUMA_GAIN_CONTROL_1 = 0x2F
ADV_REG_LUMA_GAIN_CONTROL_2 = 0x30

ADV_REG_VS_FIELD_CONTROL_1 = 0x31
ADV_REG_VS_FIELD_CONTROL_2 = 0x32
ADV_REG_VS_FIELD_CONTROL_3 = 0x33
ADV_REG_HS_POSITION_CONTROL_1 = 0x34
ADV_REG_HS_POSITION_CONTROL_2 = 0x35
ADV_REG_HS_POSITION_CONTROL_3 = 0x36
ADV_REG_POLARITY = 0x37

ADV_REG_NTSC_COMB_CONTROL = 0x38
ADV_REG_PAL_COMB_CONTROL = 0x39

ADV_REG_ADC_CONTROL = 0x3A
ADV_REG_MANUAL_WINDOW_CONTROL = 0x3D
ADV_REG_RESAMPLE_CONTROL = 0x41

ADV_REG_CTI_DNR_CONTROL_1 = 0x4D
ADV_REG_CTI_DNR_CONTROL_2 = 0x4E
ADV_REG_DNR_NOISE_THRESHOLD_1 = 0x50

ADV_REG_LOCK_COUNT = 0x51
ADV_REG_ADC_SWITCH_3 = 0x60
ADV_REG_OUTPUT_SYNC_SELECT_1 = 0x6A
ADV_REG_OUTPUT_SYNC_SELECT_2 = 0x6B
ADV_REG_FREE_RUN_LINE_LENGTH_1 = 0x8F
ADV_REG_CCAP1 = 0x99
ADV_REG_CCAP2 = 0x9A
ADV_REG_LETTERBOX_1 = 0x9B
ADV_REG_LETTERBOX_2 = 0x9C
ADV_REG_LETTERBOX_3 = 0x9D
ADV_REG_CRC_ENABLE = 0xB2
ADV_REG_ADC_SWITCH_1 = 0xC3
ADV_REG_ADC_SWITCH_2 = 0xC4
ADV_REG_LETTERBOX_CONTROL_1 = 0xDC
ADV_REG_LETTERBOX_CONTROL_2 = 0xDD
ADV_REG_ST_NOISE_READBACK_1 = 0xDE
ADV_REG_ST_NOISE_READBACK_2 = 0xDF
ADV_REG_SD_OFFSET_CB_CHANNEL = 0xE1
ADV_REG_SD_OFFSET_CR_CHANNEL = 0xE2
ADV_REG_SD_SATURATION_CB_CHANNEL = 0xE3
ADV_REG_SD_SATURATION_CR_CHANNEL = 0xE4
ADV_REG_NTSC_V_BIT_BEGIN = 0xE5
ADV_REG_NTSC_V_BIT_END = 0xE6
ADV_REG_NTSC_F_BIT_TOGGLE = 0xE7
ADV_REG_PAL_V_BIT_BEGIN = 0xE8
ADV_REG_PAL_V_BIT_END = 0xE9
ADV_REG_PAL_F_BIT_TOGGLE = 0xEA
ADV_REG_VBLANK_CONTROL_1 = 0xEB
ADV_REG_VBLANK_CONTROL_2 = 0xEC
ADV_REG_AFE_CONTROL_1 = 0xF3
ADV_REG_DRIVE_STRENGTH = 0xF4
ADV_REG_IF_COMP_CONTROL = 0xF8
ADV_REG_VS_MODE_CONTROL = 0xF9
ADV_REG_PEAKING_GAIN = 0xFB
ADV_REG_DNR_NOISE_THRESHOLD_2 = 0xFC
ADV_REG_VPP_SLAVE_ADDRESS = 0xFD
ADV_REG_CSI_TX_SLAVE_ADDRESS = 0xFE

# user sub map 2
ADV_REG_ACE_CONTROL_1 = 0x80
ADV_REG_ACE_CONTROL_4 = 0x83
ADV_REG_ACE_CONTROL_5 = 0x84
ADV_REG_ACE_CONTROL_6 = 0x85
ADV_REG_DITHER_CONTROL = 0x92
ADV_REG_MIN_MAX_0 = 0xD9
ADV_REG_MIN_MAX_1 = 0xDA
ADV_REG_MIN_MAX_2 = 0xDB
ADV_REG_MIN_MAX_3 = 0xDC
ADV_REG_MIN_MAX_4 = 0xDD
ADV_REG_MIN_MAX_5 = 0xDE
ADV_REG_FL_CONTROL = 0xE0
ADV_REG_Y_AVERAGE_0 = 0xE1
ADV_REG_Y_AVERAGE_1 = 0xE2
ADV_REG_Y_AVERAGE_2 = 0xE3
ADV_REG_Y_AVERAGE_3 = 0xE4
ADV_REG_Y_AVERAGE_4 = 0xE5
ADV_REG_Y_AVERAGE_5 = 0xE6
ADV_REG_Y_AVERAGE_DATA_MSB = 0xE7
ADV_REG_Y_AVERAGE_DATA_LSB = 0xE8
